# ============================================================================
# src/Documentation/Reporter/_build_convergence_summary_datapoints_tex.jl
#
# Author: Benjamin Jaedon Choi (https://github.com/saintbenjamin)
# Affiliation: Center for Computational Sciences, University of Tsukuba
# Address: 1-1-1 Tennodai, Tsukuba, Ibaraki 305-8577 Japan
# Contact: benchoi [at] ccs.tsukuba.ac.jp (replace [at] with @)
# License: MIT License
# ============================================================================

"""
    _build_convergence_summary_datapoints_tex(
        a, 
        b, 
        name, 
        hsp, 
        hxp, 
        estp, 
        errp;
        h_power, 
        xscale, 
        yscale, 
        rule, 
        boundary
    ) -> String

Construct a [``\\LaTeX``](https://www.latex-project.org/) datapoints-only convergence-summary fragment.

# Function description

This helper produces a [``\\LaTeX``](https://www.latex-project.org/) report fragment summarizing raw quadrature
datapoints without any fitted extrapolation model.

The generated output contains:

1. a run-configuration table,
2. a table of filtered quadrature estimates and uncertainties.

It is intended for inclusion in larger [``\\LaTeX``](https://www.latex-project.org/) documents or internal-note
workflows where the user wants to document the raw convergence data before any
fitting stage.

# Arguments

- `a`, `b`: Integration domain endpoints.

  These may be either scalars (uniform-domain case) or tuples specifying
  per-axis bounds for rectangular domains.

- `name`: Display name of the experiment or dataset.
- `hsp`: Filtered step sizes.
- `hxp`: Filtered transformed step sizes, typically ``h^{p}``.
- `estp`: Filtered quadrature estimates.
- `errp`: Filtered pointwise uncertainties.

# Keyword arguments

- `h_power`: Power used to define the horizontal coordinate ``x = h^{p}``.
- `xscale`: Horizontal axis scaling mode.
- `yscale`: Vertical axis scaling mode.
- `rule`: Quadrature rule label.
- `boundary`: Boundary-handling label.

# Returns

- `String`: [``\\LaTeX``](https://www.latex-project.org/)-formatted summary fragment.

# Notes

- No document preamble or `\\begin{document}` block is included.
- Numeric formatting relies on the internal helpers
  [`_fmt_tex_texttt_sci`](@ref) and [`_fmt_avgerr_tex`](@ref).
- The output is designed to parallel the style of
  [`_build_convergence_summary_tex`](@ref) while omitting fit-specific content.
- When any of `a`, `b`, `rule`, or `boundary` is axis-wise, the run
  configuration table expands into one row per axis.
"""
function _build_convergence_summary_datapoints_tex(
    a, 
    b, 
    name, 
    hsp, 
    hxp, 
    estp, 
    errp;
    h_power,
    xscale,
    yscale,
    rule,
    boundary,
)
    safe_name = _latex_escape_underscore(name)
    cfg_dim = _report_cfg_dim(a, b, rule, boundary)
    safe_xscale = _latex_escape_underscore(string(xscale))
    safe_yscale = _latex_escape_underscore(string(yscale))

    io = IOBuffer()

    println(io, "% Auto-generated by write_convergence_summary_datapoints")
    println(io, "")

    println(io, "\\begin{table}[ht!]")
    println(io, "\\begin{ruledtabular}")
    println(io, "\\caption{Run configuration for \\texttt{$(safe_name)}}")

    if cfg_dim == 1
        interval_txt = _latex_escape_underscore(
            _fmt_axis_interval_for_run_config(a, b, 1, 1)
        )
        rule_boundary_txt = _fmt_rule_boundary_cell_tex(rule, boundary, 1, 1)

        println(io, "\\begin{tabular}{ @{\\quad} c @{\\quad} | @{\\quad} c @{\\quad} | @{\\quad} c @{\\quad} }")
        println(io, "Interval & Rule (Boundary) & Plot setup \\\\")
        println(io, "\\hline")
        println(io,
            "\\texttt{$interval_txt} & " *
            "$rule_boundary_txt & " *
            "\$h^{$(h_power)}\$, \\texttt{$safe_xscale}/\\texttt{$safe_yscale} \\\\"
        )
    else
        println(io, "\\begin{tabular}{ @{\\quad} l @{\\quad} | @{\\quad} l @{\\quad} | @{\\quad} l @{\\quad} }")
        println(io, "Axis & Rule (Boundary) & Plot setup \\\\")
        println(io, "\\hline")
        for d in 1:cfg_dim
            axis_txt = _fmt_axis_cell_tex(a, b, d, cfg_dim)
            rule_boundary_txt = _fmt_rule_boundary_cell_tex(rule, boundary, d, cfg_dim)
            println(io,
                "$axis_txt & " *
                "$rule_boundary_txt & " *
                "\$h^{$(h_power)}\$, \\texttt{$safe_xscale}/\\texttt{$safe_yscale} \\\\"
            )
        end
    end

    println(io, "\\end{tabular}")
    println(io, "\\end{ruledtabular}")
    println(io, "\\end{table}")
    println(io, "")

    println(io, "\\begin{table}[ht!]")
    println(io, "\\begin{ruledtabular}")
    println(io, "\\caption{Quadrature estimates and uncertainties for different step sizes}")
    println(io, "\\begin{tabular}{@{\\quad} l @{\\quad} l @{\\quad} | @{\\quad} l @{\\quad}}")
    println(io, "\$h\$ & \$h^{$(h_power)}\$ & \$\\hphantom{-}I(h)\$ \\\\")
    println(io, "\\hline")

    for i in eachindex(hsp)
        htxt  = _fmt_tex_texttt_sci(hsp[i])
        hptxt = _fmt_tex_texttt_sci(hxp[i])
        qtxt  = _fmt_avgerr_tex(estp[i], abs(errp[i]))
        qtxt  = startswith(qtxt, "-") ? qtxt : "\\hphantom{-}$qtxt"
        println(io, "$htxt & $hptxt & \$$qtxt\$ \\\\")
    end

    println(io, "\\end{tabular}")
    println(io, "\\end{ruledtabular}")
    println(io, "\\end{table}")

    return String(take!(io))
end
