# ============================================================================
# src/Documentation/Reporter/_build_internal_note_figures_tex_datapoints.jl
#
# Author: Benjamin Jaedon Choi (https://github.com/saintbenjamin)
# Affiliation: Center for Computational Sciences, University of Tsukuba
# Address: 1-1-1 Tennodai, Tsukuba, Ibaraki 305-8577 Japan
# Contact: benchoi [at] ccs.tsukuba.ac.jp (replace [at] with @)
# License: MIT License
# ============================================================================

"""
    _build_internal_note_figures_tex_datapoints(
        datapoints_plot_name;
        title, 
        rule, 
        boundary, 
        h_power, 
        xscale, 
        yscale
    ) -> String

Construct a [``\\LaTeX``](https://www.latex-project.org/) figure block for a datapoints-only internal note.

# Function description

This helper generates a single-figure [``\\LaTeX``](https://www.latex-project.org/) block that includes the saved
raw-datapoints plot together with a descriptive caption summarizing:

- the quadrature rule,
- the boundary-handling scheme,
- the horizontal plotting convention ``x = h^{p}``,
- the x/y axis-scaling setup.

It is intended for inclusion in a datapoints-only internal note generated by
[`write_convergence_internal_note_datapoints`](@ref).

# Arguments

- `datapoints_plot_name`: Filename of the saved datapoints plot PDF.

# Keyword arguments

- `title`: Experiment or dataset title used in figure labels. The current
  caption text does not embed this title.
- `rule`: Quadrature rule label.
- `boundary`: Boundary-handling label.
- `h_power`: Power used in the horizontal coordinate ``x = h^{p}``.
- `xscale`: Horizontal axis scale keyword.
- `yscale`: Vertical axis scale keyword.

# Returns

- `String`: [``\\LaTeX``](https://www.latex-project.org/)-formatted code for a complete figure environment.

# Notes

- The caption uses `\\texorpdfstring` for rule and boundary strings to remain
  compatible with PDF bookmarks.
- Underscores in text-mode identifiers are escaped via
  [`_latex_escape_underscore`](@ref).
- This helper produces a single-panel figure, unlike
  [`_build_internal_note_figures_tex`](@ref), which is fit-oriented and
  two-panel.
"""
function _build_internal_note_figures_tex_datapoints(
    datapoints_plot_name::AbstractString;
    title,
    rule,
    boundary,
    h_power,
    xscale,
    yscale,
)
    safe_title = _latex_escape_underscore(title)
    safe_rule = _latex_escape_underscore(string(rule))
    safe_boundary = boundary isa Symbol ?
        _latex_escape_underscore(String(boundary)) :
        "(" * join(_latex_escape_underscore.(String.(collect(boundary))), ",\\ ") * ")"

    boundary_str = if boundary isa Symbol
        String(boundary)
    elseif boundary isa Tuple || boundary isa AbstractVector
        join(String.(boundary), "_")
    else
        String(boundary)
    end

    plain_title = title
    plain_rule = string(rule)
    plain_boundary = boundary_str

    cap_title = "\\texorpdfstring{\\texttt{$safe_title}}{$plain_title}"
    cap_rule  = "\\texorpdfstring{\\texttt{$safe_rule}}{$plain_rule}"
    cap_bound = "\\texorpdfstring{\\texttt{$safe_boundary}}{$plain_boundary}"

    io = IOBuffer()

    println(io, "% Auto-generated figure include file for datapoints-only internal note")
    println(io, "")
    println(io, "\\begin{figure}[htbp]")
    println(io, "  \\centering")
    println(io, "  \\includegraphics[width=0.48\\textwidth]{$(datapoints_plot_name)}")
    println(io,
        "  \\caption{Raw quadrature datapoints summary with rule $cap_rule and boundary $cap_bound. " *
        "The horizontal coordinate uses \$h^{$(h_power)}\$ with \\texttt{$(String(xscale))}/\\texttt{$(String(yscale))} axes.}"
    )
    println(io, "  \\label{fig:$(title)_datapoints}")
    println(io, "\\end{figure}")

    return String(take!(io))
end