# ============================================================================
# src/Documentation/Reporter/summary/_build_convergence_summary_tex.jl
#
# Author: Benjamin Jaedon Choi (https://github.com/saintbenjamin)
# Affiliation: Center for Computational Sciences, University of Tsukuba
# Address: 1-1-1 Tennodai, Tsukuba, Ibaraki 305-8577 Japan
# Contact: benchoi [at] ccs.tsukuba.ac.jp (replace [at] with @)
# License: MIT License
# ============================================================================

"""
    _build_convergence_summary_tex(
        a, 
        b, 
        name, 
        hsp, 
        hxp, 
        estp, 
        errp,
        pvec, 
        λerr, 
        fit_powers, 
        I0, 
        I0_err, 
        red, 
        nerr_terms;
        rule, 
        boundary
    ) -> String

Construct a [``\\LaTeX``](https://www.latex-project.org/) convergence-summary document fragment.

# Function description

This helper produces a set of [``\\LaTeX``](https://www.latex-project.org/) tables summarizing:

1. Fit parameters and goodness-of-fit statistics,
2. Run configuration,
3. Quadrature estimates across resolutions.

The output is intended for inclusion in larger [``\\LaTeX``](https://www.latex-project.org/) documents.

# Arguments

- `a`, `b`: Integration domain endpoints.

  These may be either scalars (uniform-domain case) or tuples specifying
  per-axis bounds for rectangular domains.

- `name`: Experiment identifier.
- `hsp`: Scalar step sizes (filtered and ordered).
- `hxp`: Transformed scalar step sizes (``h^p``).
- `estp`: Estimates at each resolution.
- `errp`: Corresponding uncertainties.
- `pvec`: Fit parameters.
- `λerr`: Parameter uncertainties.
- `fit_powers`: Model exponents.
- `I0`, `I0_err`: Extrapolated value and uncertainty.
- `red`: Reduced ``\\chi^2``.
- `nerr_terms`: Number of error terms.

# Keyword arguments

- `rule`, `boundary`: Run configuration metadata.

# Returns

- `String`: [``\\LaTeX``](https://www.latex-project.org/) code fragment.

# Notes

- No preamble or document environment is included.
- Numeric formatting uses specialized helpers for readability.
- When any of `a`, `b`, `rule`, or `boundary` is axis-wise, the run
  configuration table expands into one row per axis.
- The tabulated `h` columns always use the scalarized step sequence supplied to
  the fitter/reporting pipeline.
"""
function _build_convergence_summary_tex(
    a, 
    b, 
    name, 
    hsp, 
    hxp, 
    estp, 
    errp,
    pvec, 
    λerr, 
    fit_powers, 
    I0, 
    I0_err, 
    red, 
    nerr_terms;
    rule, 
    boundary
)

    safe_name = _latex_escape_underscore(name)
    fit_model_tex = _build_fit_model_tex(fit_powers)
    cfg_dim = _report_cfg_dim(a, b, rule, boundary)

    io = IOBuffer()

    println(io, "% Auto-generated by write_convergence_summary")
    println(io, "")

    println(io, "\\begin{table}[ht!]")
    println(io, "\\begin{ruledtabular}")
    println(io, "\\caption{Least-\$\\chi^2\$ fit results using the model \$$(fit_model_tex)\$.}")
    println(io, "\\begin{tabular}{ @{\\quad} c @{\\quad} | @{\\quad} l @{\\quad} }")
    println(io, "parameter & \$\\hphantom{-}\$fit result \\\\")
    println(io, "\\hline")
    for i in eachindex(pvec)
        is_const = (fit_powers[i] == 0)

        λname = is_const ? raw"$\lambda_0$" : "\$\\lambda_$(i-1)\$"
        λtxt  = _fmt_avgerr_tex(pvec[i], λerr[i])

        aligned = startswith(λtxt, "-") ? λtxt : "\\hphantom{-}$λtxt"
        valtex = is_const ? "\\mathbf{$aligned}" : aligned

        println(io, "$λname & \$$valtex\$ \\\\")
    end
    println(io, "\\hline")
    red_txt = _fmt_tex_texttt_sci(red)
    red_txt = startswith(red_txt, "-") ? red_txt : "\$\\hphantom{-}\$$red_txt"
    println(io, "\$\\chi^2/\\mathrm{d.o.f.}\$ & $red_txt \\\\")
    println(io, "\\end{tabular}")
    println(io, "\\end{ruledtabular}")
    println(io, "\\end{table}")
    println(io, "")

    println(io, "\\begin{table}[ht!]")
    println(io, "\\begin{ruledtabular}")
    println(io, "\\caption{Run configuration for \\texttt{$(safe_name)}}")

    if cfg_dim == 1
        interval_txt = _latex_escape_underscore(
            _fmt_axis_interval_for_run_config(a, b, 1, 1)
        )
        rule_boundary_txt = _fmt_rule_boundary_cell_tex(rule, boundary, 1, 1)

        if nerr_terms == 0
            println(io, "\\begin{tabular}{ @{\\quad} c @{\\quad} | @{\\quad} c @{\\quad} }")
            println(io, "Interval & Rule (Boundary) \\\\")
            println(io, "\\hline")
            println(io, "\\texttt{$interval_txt} & $rule_boundary_txt \\\\")
        else
            println(io, "\\begin{tabular}{ @{\\quad} c @{\\quad} | @{\\quad} c @{\\quad} | @{\\quad} c @{\\quad} }")
            println(io, "Interval & Rule (Boundary) & Number of error terms \\\\")
            println(io, "\\hline")
            println(io, "\\texttt{$interval_txt} & $rule_boundary_txt & \$$(nerr_terms)\$ \\\\")
        end
    else
        if nerr_terms == 0
            println(io, "\\begin{tabular}{ @{\\quad} l @{\\quad} | @{\\quad} l @{\\quad} }")
            println(io, "Axis & Rule (Boundary) \\\\")
            println(io, "\\hline")
            for d in 1:cfg_dim
                axis_txt = _fmt_axis_cell_tex(a, b, d, cfg_dim)
                rule_boundary_txt = _fmt_rule_boundary_cell_tex(rule, boundary, d, cfg_dim)
                println(io, "$axis_txt & $rule_boundary_txt \\\\")
            end
        else
            println(io, "\\begin{tabular}{ @{\\quad} l @{\\quad} | @{\\quad} l @{\\quad} | @{\\quad} c @{\\quad} }")
            println(io, "Axis & Rule (Boundary) & Number of error terms \\\\")
            println(io, "\\hline")
            for d in 1:cfg_dim
                axis_txt = _fmt_axis_cell_tex(a, b, d, cfg_dim)
                rule_boundary_txt = _fmt_rule_boundary_cell_tex(rule, boundary, d, cfg_dim)
                println(io, "$axis_txt & $rule_boundary_txt & \$$(nerr_terms)\$ \\\\")
            end
        end
    end

    println(io, "\\end{tabular}")
    println(io, "\\end{ruledtabular}")
    println(io, "\\end{table}")
    println(io, "")

    println(io, "\\begin{table}[ht!]")
    println(io, "\\begin{ruledtabular}")
    println(io, "\\caption{Quadrature estimates and uncertainties for different step sizes}")
    println(io, "\\begin{tabular}{@{\\quad} l @{\\quad} l @{\\quad} | @{\\quad} l @{\\quad}}")
    println(io, "\$h\$ & \$h^{$(fit_powers[2])}\$ & \$\\hphantom{-}I(h)\$ \\\\")
    println(io, "\\hline")
    for i in eachindex(hsp)
        htxt  = _fmt_tex_texttt_sci(hsp[i])
        hptxt = _fmt_tex_texttt_sci(hxp[i])
        qtxt  = _fmt_avgerr_tex(estp[i], abs(errp[i]))
        qtxt = startswith(qtxt, "-") ? qtxt : "\\hphantom{-}$qtxt"
        println(io, "$htxt & $hptxt & \$$qtxt\$ \\\\")
    end
    println(io, "\\hline")
    htxt  = _fmt_tex_texttt_sci(0.0)
    hptxt = _fmt_tex_texttt_sci(0.0)
    qtxt  = _fmt_avgerr_tex(I0, I0_err)
    qtxt = startswith(qtxt, "-") ? qtxt : "\\hphantom{-}$qtxt"
    println(io, "$htxt & $hptxt & \$\\mathbf{$qtxt}\$ \\\\")
    println(io, "\\end{tabular}")
    println(io, "\\end{ruledtabular}")
    println(io, "\\end{table}")

    return String(take!(io))
end
