# ============================================================================
# src/ErrorEstimate/ErrorBSpline.jl
#
# Author: Benjamin Jaedon Choi (https://github.com/saintbenjamin)
# Affiliation: Center for Computational Sciences, University of Tsukuba
# Address: 1-1-1 Tennodai, Tsukuba, Ibaraki 305-8577 Japan
# Contact: benchoi [at] ccs.tsukuba.ac.jp (replace [at] with @)
# License: MIT License
# ============================================================================

"""
    module ErrorBSpline

B-spline-specific error-estimation layer for `Maranatha.jl`.

`Maranatha.ErrorEstimate.ErrorBSpline` provides error estimators tailored to
composite B-spline quadrature rules. It combines two complementary strategies:

1. derivative-informed residual models based on midpoint moment analysis,
2. refinement-based estimators based on coarse–versus–fine quadrature differences.

These estimators mirror the Gauss and Newton–Cotes pipelines but operate on
B-spline quadrature rules generated by [`BSpline.bspline_nodes_weights`](@ref).

---

## Role in the overall error-estimation architecture

Within the `Maranatha.ErrorEstimate` subsystem, this module implements the
B-spline branch of the error-estimation dispatch tree:

| Layer | Responsibility |
|:------|:---------------|
| ErrorDispatch | selects rule-family backend |
| ErrorBSpline | implements B-spline estimators |
| ErrorBSplineDerivative | derivative-based residual models |
| ErrorBSplineRefinement | refinement-difference estimators |

---

## Available estimation strategies

### Derivative-based (residual) estimators

Provided by [`ErrorBSplineDerivative`](@ref):

* Detect leading midpoint-centered residual terms of the composite rule
* Construct asymptotic truncation-error models using derivatives
* Compatible with the global derivative backend system
  (`ForwardDiff`, `TaylorSeries`, `Enzyme`, etc.)

These estimators are most useful when:

* the integrand is smooth,
* derivative information is reliable,
* asymptotic convergence behavior is of interest.

---

### Refinement-based estimators

Provided by [`ErrorBSplineRefinement`](@ref):

* Compare quadrature with subdivision counts `N` and `2N`
* Use the absolute difference as an effective error scale
* Do not require derivatives or residual moments

These estimators are particularly robust when:

* derivative evaluation is difficult or unstable,
* the integrand is non-smooth,
* a conservative empirical error scale is desired.

---

## Typical usage

End users normally do not call this module directly.  
Instead, B-spline error estimation is selected automatically through the
higher-level dispatcher:

```julia
Maranatha.ErrorEstimate.ErrorDispatch.error_estimate(...)
```

based on the chosen quadrature rule.

---

## Notes

* All routines assume tensor-product B-spline quadrature on hypercubes
  `[a, b]^dim`.
* Smoothing spline rules accept a nonnegative parameter `λ`, while
  interpolation rules ignore it.
* The returned error values represent **effective scales for downstream
  weighting**, not guaranteed strict truncation bounds.
"""
module ErrorBSpline

import ..JobLoggerTools
import ..Quadrature.BSpline

include("ErrorBSplineDerivative.jl")
include("ErrorBSplineRefinement.jl")

using .ErrorBSplineDerivative
using .ErrorBSplineRefinement

end  # module ErrorBSpline
